// <auto-generated />
using Intellinode.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Intellinode.Infrastructure.Persistence.Migrations;

[DbContext(typeof(IntellinodeDbContext))]
[Migration("20260527120000_AddDiscoverLookupAndEnrollmentStates")]
partial class AddDiscoverLookupAndEnrollmentStates
{
    /// <inheritdoc />
    protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
    }
}
