// <auto-generated />
using Intellinode.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Intellinode.Infrastructure.Persistence.Migrations;

[DbContext(typeof(IntellinodeDbContext))]
[Migration("20260528120000_BackfillDiscoverLookupForActiveDevices")]
partial class BackfillDiscoverLookupForActiveDevices
{
    /// <inheritdoc />
    protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
    }
}
