// <auto-generated />
using Intellinode.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Intellinode.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntellinodeDbContext))]
    [Migration("20260615160000_AddDeviceWindowsUserInterfaceSettings")]
    partial class AddDeviceWindowsUserInterfaceSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is maintained in IntellinodeDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
