// <auto-generated />
using System;
using Intellinode.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intellinode.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntellinodeDbContext))]
    [Migration("20260523055049_InitialIntellinodeSchema")]
    partial class InitialIntellinodeSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("intellinode")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enrollment_state", "intellinode", new[] { "PendingInventory", "Active", "Unlicensed", "Disabled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "heartbeat_binding_kind", "intellinode", new[] { "IpAddress", "HostName" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intellinode.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_user_name");

                    b.ToTable("admin_users", "intellinode");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.AgentEnrollmentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsumedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_utc");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_admin_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("mac_address");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_agent_enrollment_tokens");

                    b.HasIndex("CreatedByAdminId")
                        .HasDatabaseName("ix_agent_enrollment_tokens_created_by_admin_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_agent_enrollment_tokens_device_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_enrollment_tokens_token_hash");

                    b.ToTable("agent_enrollment_tokens", "intellinode");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.AgentRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_agent_refresh_tokens");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_agent_refresh_tokens_device_id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_agent_refresh_tokens_token_hash");

                    b.ToTable("agent_refresh_tokens", "intellinode");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentUpTime")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_up_time");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_version");

                    b.Property<string>("ClientStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_status");

                    b.Property<string>("CommunicationIpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("communication_ip_address");

                    b.Property<string>("CommunicationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("communication_type");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("duration");

                    b.Property<int>("EnrollmentState")
                        .HasColumnType("intellinode.enrollment_state")
                        .HasColumnName("enrollment_state");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gateway");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host_name");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDhcp")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dhcp");

                    b.Property<bool>("IsDomainJoined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_domain_joined");

                    b.Property<bool>("IsLicensed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_licensed");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_registered");

                    b.Property<bool>("IsServiceMode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_service_mode");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_key");

                    b.Property<string>("LoginUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_user_name");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("os");

                    b.Property<string>("OsVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("os_version");

                    b.Property<int>("PollInterval")
                        .HasColumnType("integer")
                        .HasColumnName("poll_interval");

                    b.Property<string>("PrimaryDns")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_dns");

                    b.Property<string>("PrimaryWins")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_wins");

                    b.Property<string>("SecondaryDns")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secondary_dns");

                    b.Property<string>("SecondaryWins")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secondary_wins");

                    b.Property<string>("SubnetMask")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subnet_mask");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.Property<string>("Workgroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workgroup");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_devices_group_id");

                    b.HasIndex("TenantId", "MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_tenant_id_mac_address");

                    b.ToTable("devices", "intellinode");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.DeviceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_device_groups");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_device_groups_tenant_id_name");

                    b.ToTable("device_groups", "intellinode");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.DeviceInventory", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("CollectedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_utc");

                    b.Property<string>("HardwareJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("hardware");

                    b.Property<string>("NetworkJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("network");

                    b.Property<string>("OsInfoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("os_info");

                    b.Property<string>("SecurityJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("security");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("DeviceId")
                        .HasName("pk_device_inventory");

                    b.ToTable("device_inventory", "intellinode");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.DeviceTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_utc");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ExtraData")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("extra_data");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("function_name");

                    b.Property<string>("FunctionParameter")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("function_parameter");

                    b.Property<int>("LegacyTaskId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_task_id");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("module_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_device_tasks");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_tasks_device_id");

                    b.ToTable("device_tasks", "intellinode");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.HeartbeatBindingChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangedValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("changed_value");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsBindingActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_binding_active");

                    b.Property<bool>("IsServiceMode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_service_mode");

                    b.Property<int>("Kind")
                        .HasColumnType("intellinode.heartbeat_binding_kind")
                        .HasColumnName("kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_heartbeat_binding_changes");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_heartbeat_binding_changes_device_id");

                    b.ToTable("heartbeat_binding_changes", "intellinode");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("HostName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", "intellinode");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.AgentEnrollmentToken", b =>
                {
                    b.HasOne("Intellinode.Domain.Entities.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_agent_enrollment_tokens_admin_users_created_by_admin_id");

                    b.HasOne("Intellinode.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_agent_enrollment_tokens_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.AgentRefreshToken", b =>
                {
                    b.HasOne("Intellinode.Domain.Entities.Device", "Device")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_refresh_tokens_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.Device", b =>
                {
                    b.HasOne("Intellinode.Domain.Entities.DeviceGroup", "Group")
                        .WithMany("Devices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_devices_device_groups_group_id");

                    b.HasOne("Intellinode.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Devices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_tenants_tenant_id");

                    b.Navigation("Group");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.DeviceGroup", b =>
                {
                    b.HasOne("Intellinode.Domain.Entities.Tenant", "Tenant")
                        .WithMany("DeviceGroups")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_groups_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.DeviceInventory", b =>
                {
                    b.HasOne("Intellinode.Domain.Entities.Device", "Device")
                        .WithOne("Inventory")
                        .HasForeignKey("Intellinode.Domain.Entities.DeviceInventory", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_inventory_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.DeviceTask", b =>
                {
                    b.HasOne("Intellinode.Domain.Entities.Device", "Device")
                        .WithMany("Tasks")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_tasks_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.HeartbeatBindingChange", b =>
                {
                    b.HasOne("Intellinode.Domain.Entities.Device", "Device")
                        .WithMany("BindingChanges")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_heartbeat_binding_changes_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.Device", b =>
                {
                    b.Navigation("BindingChanges");

                    b.Navigation("Inventory");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.DeviceGroup", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Intellinode.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("DeviceGroups");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
