// <auto-generated />
using Intellinode.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Intellinode.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntellinodeDbContext))]
    [Migration("20260526140000_AddDeviceRemoteSettingsPhase2")]
    partial class AddDeviceRemoteSettingsPhase2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
        {
        }
    }
}
